apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
  namespace: openshift-gitops
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: mesh_gitops
    repoURL: https://github.com/agabriel81/terraform-aro.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
