kind: Project
apiVersion: project.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: bookinfo
spec:
  finalizers:
    - kubernetes
---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: istio-system
spec:
  finalizers:
    - kubernetes
