apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/kiali-ossm.openshift-operators: ""
  name: kiali-ossm
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kiali-operator.v1.73.7
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  labels:
    operators.coreos.com/servicemeshoperator.openshift-operators: ""
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: servicemeshoperator.v2.5.1
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - maistra.io/istio-operator
  name: basic
  namespace: istio-system
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    egress:
      enabled: true
    ingress:
      enabled: true
      runtime:
        deployment:
          autoScaling:
            enabled: false
          replicas: 3
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringScheduling:
              - key: app
                operator: In
                topologyKey: topology.kubernetes.io/zone
                values:
                - istio-ingressgateway
      volumes:
      - volume:
          secret:
            secretName: istio-ingressgateway-customer-certs
        volumeMount:
          mountPath: /etc/istio/customer-certs
          name: customer-certs
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  profiles:
  - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.5
---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: bookinfo
spec:
  finalizers:
    - kubernetes
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
annotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - maistra.io/istio-operator
  name: default
  namespace: istio-system
spec:
  members:
  - bookinfo
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: istio-ingressgateway
  name: trafficmanager-route
  namespace: istio-system
spec:
  host: agabriel-tm-test.trafficmanager.net
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
